[package]

name = "rlex2"
version = "0.0.1"
authors = ["Gulshan Singh <gulshan@umich.edu>"]

[dependencies.parse-regex]
path = "/home/gulshan/code/lang/rust/parse-regex"

[dependencies.automata]
path = "/home/gulshan/code/lang/rust/automata"
